# Generated by Django 4.0.5 on 2023-01-13 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_core_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealimage',
            name='url',
        ),
        migrations.AlterField(
            model_name='mealclick',
            name='click_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 7, 41, 11, 108255, tzinfo=utc), verbose_name='Дата клика'),
        ),
    ]
